export const Routes = {
  AUTH: {
    ROOT: '/(auth)',
    LOGIN: '/login',
    CAMBIAR_PASSWORD: '/cambiar-password',
  },
  TABS: {
    ROOT: '/(app)',
    DASHBOARD: '/dashboard',
    CLIENTES: '/clientes',
    CLIENTES_DETALLE: (id: string) => `/clientes/${id}` as const,
    PRESTAMOS: '/prestamos',
    PRESTAMOS_NUEVO: '/prestamos/nuevo',
    PRESTAMOS_DETALLE: (id: string) => `/prestamos/${id}` as const,
    PAGOS: '/pagos',
    PAGOS_PRESTAMO: (id: string) => `/pagos/${id}` as const,
    RUTAS: '/rutas',
    RUTAS_DETALLE: (id: string) => `/rutas/${id}` as const,
    PERFIL: '/perfil',
    CONFIGURACION: '/perfil/configuracion',
  },
  ADMIN: {
    ALERTAS: '/admin/alertas',
    ANALISIS_RUTAS: '/admin/analisis-rutas',
    EMPLEADOS: '/admin/empleados',
    ESTADO_FINANCIERO: '/admin/estado-financiero',
    GASTOS: '/admin/gastos',
    USUARIOS: '/admin/usuarios',
    REPORTES: '/admin/reportes',
    CONFIGURACION: '/admin/configuracion',
  },
  ROOT: '/',
  INDEX: '/',
} as const;
