export const PROVINCIAS_MUNICIPIOS: Record<string, string[]> = {
  "Azua": [
    "Azua", "Estebanía", "Guayabal", "Las Charcas", "Las Yayas de Viajama",
    "Padre Las Casas", "Peralta", "Pueblo Viejo", "Sabana Yegua", "Tábara Arriba",
  ],
  "Bahoruco": ["Neyba", "Galván", "Los Ríos", "Tamayo", "Villa Jaragua"],
  "Barahona": [
    "Barahona", "Cabral", "El Peñón", "Enriquillo", "Fundación",
    "Jaquimeyes", "La Ciénaga", "Las Salinas", "Paraíso", "Polo", "Vicente Noble",
  ],
  "Dajabón": ["Dajabón", "El Pino", "Loma de Cabrera", "Partido", "Restauración"],
  "Distrito Nacional": ["Santo Domingo de Guzmán"],
  "Duarte": [
    "San Francisco de Macorís", "Arenoso", "Castillo", "Eugenio María de Hostos",
    "Las Guáranas", "Pimentel", "Villa Riva",
  ],
  "El Seibo": ["El Seibo", "Miches"],
  "Elías Piña": ["Comendador", "Bánica", "El Llano", "Hondo Valle", "Juan Santiago", "Pedro Santana"],
  "Espaillat": ["Moca", "Cayetano Germosén", "Gaspar Hernández", "Jamao al Norte"],
  "Hato Mayor": ["Hato Mayor", "El Valle", "Sabana de la Mar"],
  "Hermanas Mirabal": ["Salcedo", "Tenares", "Villa Tapia"],
  "Independencia": ["Jimaní", "Cristóbal", "Duvergé", "La Descubierta", "Mella", "Postrer Río"],
  "La Altagracia": ["Higüey", "San Rafael del Yuma"],
  "La Romana": ["La Romana", "Casa de Campo", "Guaymate", "Villa Hermosa"],
  "La Vega": ["La Vega", "Constanza", "Jarabacoa", "Jima Abajo"],
  "María Trinidad Sánchez": ["Nagua", "Cabrera", "El Factor", "Río San Juan"],
  "Monseñor Nouel": ["Bonao", "Maimón", "Piedra Blanca"],
  "Monte Cristi": ["Monte Cristi", "Castañuelas", "Guayubín", "Las Matas de Santa Cruz", "Pepillo Salcedo", "Villa Vásquez"],
  "Monte Plata": ["Monte Plata", "Bayaguana", "Peralvillo", "Sabana Grande de Boyá", "Yamasá"],
  "Pedernales": ["Pedernales", "Oviedo"],
  "Peravia": ["Baní", "Nizao"],
  "Puerto Plata": ["Puerto Plata", "Altamira", "Guananico", "Imbert", "Los Hidalgos", "Luperón", "Sosúa", "Villa Isabela", "Villa Montellano"],
  "Samaná": ["Samaná", "Las Terrenas", "Sánchez"],
  "San Cristóbal": ["San Cristóbal", "Bajos de Haina", "Cambita Garabitos", "Los Cacaos", "Sabana Grande de Palenque", "San Gregorio de Nigua", "Villa Altagracia", "Yaguate"],
  "San José de Ocoa": ["San José de Ocoa", "Rancho Arriba", "Sabana Larga"],
  "San Juan": ["San Juan de la Maguana", "Bohechío", "El Cercado", "Juan de Herrera", "Las Matas de Farfán", "Vallejuelo"],
  "San Pedro de Macorís": ["San Pedro de Macorís", "Consuelo", "Guayacanes", "Quisqueya", "Ramón Santana", "San José de Los Llanos"],
  "Sánchez Ramírez": ["Cotuí", "Cevicos", "Fantino", "La Mata"],
  "Santiago": ["Santiago de los Caballeros", "Bisonó", "Jánico", "Licey al Medio", "Puñal", "Sabana Iglesia", "San José de Las Matas", "Tamboril", "Villa González"],
  "Santiago Rodríguez": ["Sabaneta", "Los Almácigos", "Monción"],
  "Santo Domingo": ["Santo Domingo Este", "Santo Domingo Norte", "Santo Domingo Oeste", "Boca Chica", "Los Alcarrizos", "Pedro Brand", "San Antonio de Guerra"],
  "Valverde": ["Mao", "Esperanza", "Laguna Salada"],
};

export const PROVINCIAS = Object.keys(PROVINCIAS_MUNICIPIOS).sort();

export const SECTORES_POR_MUNICIPIO: Record<string, string[]> = {
  "Santo Domingo de Guzmán": [
    "Gazcue", "Ciudad Nueva", "Ciudad Universitaria", "Villa Juana", "Villa Consuelo",
    "Mejoramiento Social", "Quisqueya", "Cristo Rey", "Simón Bolívar", "Los Jardines",
    "Zona Colonial", "Naco", "Piantini", "Bella Vista", "Evaristo Morales",
    "La Esperilla", "Los Cacicazgos", "Viejo Arroyo Hondo", "Altos de Arroyo Hondo",
    "Arroyo Hondo", "La Julia", "Mirador Norte", "Mirador Sur", "El Millón",
    "Alma Rosa", "Buenos Aires", "La Fe", "San Carlos", "Villas Agrícolas",
    "Los Mameyes", "Ensanche Ozama", "La Victoria", "Sabana Perdida",
    "Villa Duarte", "San Luis", "Ensanche Isabelita", "Ensanche Capotillo",
    "La Ciénaga", "Los Guandules", "Gualey", "24 de Abril", "Domingo Savio",
    "Libertador", "Ensanche Luperón", "Ensanche La Paz",
    "Las Caobas", "El Pedregal", "Pueblo Nuevo", "Ensanche Espaillat",
  ],
  "Santo Domingo Este": [
    "San Isidro", "Las Américas", "Alma Rosa I", "Alma Rosa II", "Ensanche Ozama",
    "Villa Duarte", "La Caleta", "Mendoza", "Manoguayabo Este", "Brisa del Este",
    "Ensanche Isabelita", "Los Tres Brazos", "La Romana", "El Tamarindo",
    "Parque Tropical", "Palacio", "La Zurza Este", "Los Mameyes Este",
    "Sabana Perdida", "Sabana Perdida Norte", "Villa Faro", "Ciudad Ozama",
  ],
  "Santo Domingo Norte": [
    "La Victoria", "Sabana Perdida", "Villa Mella", "Los Alcarrizos Norte",
    "Guaricano", "Los Peralejos", "Palmarejo", "Palmar Arriba", "Palma Real",
    "Pantoja", "El Embrujo", "Loma Linda", "Boca del Rio", "La Zurza",
  ],
  "Santo Domingo Oeste": [
    "Manoguayabo", "Herrera", "Boca Chica Oeste", "Jardines del Sur",
    "Palmarejo", "La Agustina", "Mejoramiento Social Oeste", "La Zurza Oeste",
  ],
  "Boca Chica": ["Boca Chica", "La Caleta", "Andrés", "Punta Prieta", "Los Tres Brazos", "Playa Boca Chica", "Don Juan"],
  "Los Alcarrizos": ["Los Alcarrizos", "Pedro Brand", "Palmarejo", "Nueva Barquita", "La Barquita", "Mata Hambre", "Las Palmas"],
  "Santiago de los Caballeros": [
    "Centro de la Ciudad", "Los Jardines Metropolitanos", "Bella Vista Santiago",
    "Pekín", "El Embrujo", "Las Colinas", "Villa Olga", "Gurabo", "Cienfuegos",
    "Nibaje", "Los Salados", "Los Jardines", "Metropolitano", "Villa Progreso",
    "Las Mercedes", "Brisas del Yaque", "La Trinitaria", "Los Pepines",
    "Mejoramiento Social Santiago", "Villa Linda", "Ensanche Bermúdez",
    "Reparto Conrado", "Punta Blanca", "Los Limones", "Barrio Obrero",
    "Pueblo Nuevo Santiago", "Jacagua", "Hato Mayor Santiago", "Navarrete",
    "Unión Panamericana",
  ],
  "San Francisco de Macorís": [
    "Centro", "La Yuca", "Villa Taína", "Los Cocos", "Barrio Nuevo",
    "La Altagracia", "La Joya", "Las Flores", "Villa Esperanza", "El Amparo",
    "Barrio Obrero", "Villa Francisca", "Las Mercedes", "El Bosque",
    "La Guardia", "El Cementerio", "Altos de la Yuca", "La Lomita",
    "Villa Clara", "El Pozo", "Villa Luz", "Barrio 19 de Marzo",
  ],
  "La Vega": [
    "Centro La Vega", "Pueblo Nuevo La Vega", "Los Pepines La Vega",
    "La Herradura", "El Ranchito", "Las Calderas", "Vuelta Larga",
    "Rincón", "Las Circunstancias", "El Toro", "Sabana Iglesia La Vega",
  ],
  "San Pedro de Macorís": [
    "Centro", "Los Corales", "El Caliche", "Barrio Obrero San Pedro",
    "Villa Olga San Pedro", "Miramar", "Las Flores San Pedro",
    "Restauración", "Los Municipios", "El Ingenio", "Mella",
    "Batey Bienvenido", "Quisqueya", "Consuelo",
  ],
  "La Romana": [
    "Centro La Romana", "Villa Hermosa", "Santa Rosa", "Los Tres Ojos",
    "Barrio Obrero La Romana", "Caleta", "La Ensenada", "Nuevo Boca Chica",
    "Porvenir", "El Caliche La Romana",
  ],
  "Higüey": [
    "Centro Higüey", "Los Lirios", "El Macao", "Veron-Punta Cana",
    "Friusa", "El Cortecito", "Bávaro", "Los Corales", "Uvero Alto",
    "La Otra Banda", "Cruce de El Macao",
  ],
  "Puerto Plata": [
    "Centro Puerto Plata", "Los Jardines Puerto Plata", "Villa Progreso",
    "Gregorio Luperón", "La Javilla", "Montellano", "Long Beach",
    "Playa Dorada", "Costambar", "El Cupey",
  ],
  "Sosúa": ["Sosúa", "El Batey", "Los Charamicos"],
  "Barahona": ["Centro Barahona", "Barrio Nuevo Barahona", "Los Patos", "Las Filipinas", "El Cachón", "Villa Central", "Arroyo Dulce"],
  "Azua": ["Centro Azua", "Las Charcas", "Los Jovillos", "Villa Nizao", "El Número", "Buen Precio", "Las Barías"],
  "San Juan de la Maguana": ["Centro San Juan", "El Cercado", "Pedro Corto", "Sabaneta San Juan", "Las Matas", "Hato Nuevo", "Las Charcas San Juan"],
  "Baní": ["Centro Baní", "Villa Baní", "Los Quemados", "Palmar", "El Piro", "Matanzas", "Arroyo Salado", "Sabana Buey"],
  "San Cristóbal": ["Centro San Cristóbal", "Sainaguá", "La Toma", "Hato Damas", "Tres Pasos", "Nigua", "Los Mosquitos", "Bajos de Haina", "Villa Altagracia", "Cambita"],
  "Moca": ["Centro Moca", "Los Montones", "Villa Tapia Moca", "Palmar Chico", "La Palma", "Canca La Reyna", "Arroyo Toro"],
  "Constanza": ["Constanza", "La Culata", "Tireo", "Valle Nuevo"],
  "Jarabacoa": ["Jarabacoa", "Manabao", "La Ciénaga de Manabao", "Buena Vista"],
  "Nagua": ["Centro Nagua", "Las Gordas", "La Entrada", "El Café"],
  "Bonao": ["Centro Bonao", "La Cuchilla", "Río Blanco", "Jayaco", "Sabana del Puerto"],
  "Cotuí": ["Centro Cotuí", "Fantino", "Cevicos", "La Mata"],
  "Hato Mayor": ["Centro Hato Mayor", "El Valle", "Sabana de la Mar", "Yerba Buena"],
  "El Seibo": ["Centro El Seibo", "Miches", "Los Llanos El Seibo"],
  "Monte Plata": ["Centro Monte Plata", "Yamasá", "Bayaguana", "Peralvillo"],
  "Mao": ["Centro Mao", "Esperanza", "Laguna Salada Valverde"],
  "Samaná": ["Santa Bárbara de Samaná", "El Limón", "Las Terrenas", "Las Galeras"],
  "Pedernales": ["Centro Pedernales", "Oviedo", "Juancho"],
  "Monte Cristi": ["Centro Monte Cristi", "Guayubín", "Manzanillo"],
  "Jimaní": ["Centro Jimaní", "La Descubierta", "Duvergé", "Cristóbal"],
  "Dajabón": ["Dajabón", "Loma de Cabrera", "Restauración Dajabón"],
  "Comendador": ["Comendador", "Bánica", "El Llano", "Hondo Valle"],
  "Salcedo": ["Centro Salcedo", "Tenares", "Villa Tapia Mirabal"],
  "San José de Ocoa": ["Centro Ocoa", "Rancho Arriba", "Sabana Larga", "La Ciénaga Ocoa"],
  "Sabaneta": ["Sabaneta", "Los Almácigos", "Monción"],
  "Esperanza": ["Esperanza", "Magante", "Buen Hombre"],
};

export function getSectores(municipio: string): string[] {
  return SECTORES_POR_MUNICIPIO[municipio] ?? [];
}
